server.port=8080
# ─── SQL Server ───
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=manga_studio;encrypt=false;trustServerCertificate=true
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
# ─── JWT ───
app.jwt.secret=MangaFlowSecretKeyForJWTTokenGeneration2024AtLeast256BitsLong
app.jwt.expiration=86400000
# ─── File Upload ───
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB
# ─── Cloudinary ───
cloudinary.cloud-name=dklp7kcl9
cloudinary.api-key=695997117426795
cloudinary.api-secret=eZD9UJBGUWljBE_1VxmzvJTjOT4
# ─── Swagger / Springdoc ───
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true
# In SQL, request, response chi tiết
logging.level.com.mangaflow.studio=DEBUG
logging.level.org.springframework.security=INFO